spring:
  application:
    name: tanzu-java-web-app
management:
  server:
    port: "8082"
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
