apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app-prometheus-without-annotations
  annotations:
    prometheus.io/scrape: "false"
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app-prometheus-without-annotations
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/ksankaranara-vmw/tanzu-java-web-app-prometheus
      ref:
        branch: main
